Repository Team-B1ND/dodamdodam-android, pull requests merged in 2024-03, with the labels that each got.

#47 [Designsystem] Create ask card component
  designsystem/build.gradle.kts
  designsystem/src/main/java/com/b1nd/dodam/designsystem/component/Card.kt
  designsystem/src/main/java/com/b1nd/dodam/designsystem/component/Progress.kt
  designsystem/src/main/java/com/b1nd/dodam/designsystem/component/TopAppBar.kt
  designsystem/src/main/java/com/b1nd/dodam/designsystem/model/AskStatus.kt
Labels: enhancement

#50 [Network] Fix error handler
  common/src/main/java/com/b1nd/dodam/common/exception/DodamException.kt
  common/src/main/java/com/b1nd/dodam/common/result/Result.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/HomeViewModel.kt
  feature/login/src/main/java/com/b1nd/dodam/login/viewmodel/LoginViewModel.kt
  feature/meal/src/main/java/com/b1nd/dodam/meal/viewmodel/MealViewModel.kt
  feature/register/src/main/java/com/b1nd/dodam/register/viewmodel/RegisterViewModel.kt
  network/core/src/main/java/com/b1nd/dodam/network/core/di/NetworkModule.kt
  network/core/src/main/java/com/b1nd/dodam/network/core/model/Response.kt
  network/core/src/main/java/com/b1nd/dodam/network/core/util/ApiRequest.kt
  network/login/src/main/java/com/b1nd/dodam/network/login/api/LoginService.kt
  network/login/src/test/java/com/b1nd/dodam/network/login/LoginServiceTest.kt
Labels: bug

#51 [Meal] Fix meal screen
  feature/meal/src/main/java/com/b1nd/dodam/meal/MealScreen.kt
Labels: refactoring

#52 [NightStudy] Create night study
  data/core/src/main/java/com/b1nd/dodam/data/core/model/Status.kt
  data/night-study/build.gradle.kts
  designsystem/src/main/java/com/b1nd/dodam/designsystem/component/BottomNavigation.kt
  designsystem/src/main/java/com/b1nd/dodam/designsystem/component/Card.kt
  designsystem/src/main/java/com/b1nd/dodam/designsystem/icons/Plus.kt
  designsystem/src/main/java/com/b1nd/dodam/designsystem/icons/SmailMoon.kt
  dodam-student/build.gradle.kts
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  feature-student/main/build.gradle.kts
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/MainScreen.kt
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/navigation/MainNavigation.kt
  feature-student/nightstudy/.gitignore
  feature-student/nightstudy/build.gradle.kts
  feature-student/nightstudy/consumer-rules.pro
  feature-student/nightstudy/proguard-rules.pro
  feature-student/nightstudy/src/main/AndroidManifest.xml
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/NightStudyScreen.kt
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/NightStudyUiState.kt
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/navigation/NightStudyNavigation.kt
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/viewmodel/NightStudyViewModel.kt
  feature/meal/src/main/java/com/b1nd/dodam/meal/MealScreen.kt
  gradle/libs.versions.toml
  settings.gradle.kts
  ui-test-main/src/main/kotlin/com/b1nd/dodam/test/DodamApp.kt
Labels: enhancement

#55 feat: Add dodam segmented button component
  designsystem/src/main/java/com/b1nd/dodam/designsystem/component/Button.kt
Labels: enhancement

#58 [Outing] Create outing screen
  designsystem/src/main/java/com/b1nd/dodam/designsystem/component/Button.kt
  designsystem/src/main/java/com/b1nd/dodam/designsystem/component/Card.kt
  designsystem/src/main/java/com/b1nd/dodam/designsystem/component/TopAppBar.kt
  designsystem/src/main/java/com/b1nd/dodam/designsystem/icons/ConvenienceStore.kt
  designsystem/src/main/java/com/b1nd/dodam/designsystem/icons/Tent.kt
  dodam-student/build.gradle.kts
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  feature-student/main/build.gradle.kts
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/MainScreen.kt
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/navigation/MainNavigation.kt
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/NightStudyScreen.kt
  feature-student/outing/.gitignore
  feature-student/outing/build.gradle.kts
  feature-student/outing/consumer-rules.pro
  feature-student/outing/proguard-rules.pro
  feature-student/outing/src/main/AndroidManifest.xml
  feature-student/outing/src/main/java/com/b1nd/dodam/outing/OutingScreen.kt
  feature-student/outing/src/main/java/com/b1nd/dodam/outing/OutingUiState.kt
  feature-student/outing/src/main/java/com/b1nd/dodam/outing/nanigation/OutingNavigation.kt
  feature-student/outing/src/main/java/com/b1nd/dodam/outing/viewmodel/OutingViewModel.kt
  settings.gradle.kts
  ui-test-main/src/main/kotlin/com/b1nd/dodam/test/DodamApp.kt
Labels: enhancement

#60 [Meal] Add meal empty screen
  designsystem/src/main/res/drawable/ic_empty.xml
  feature/meal/src/main/java/com/b1nd/dodam/meal/MealScreen.kt
  feature/meal/src/main/java/com/b1nd/dodam/meal/MealUiState.kt
Labels: enhancement

#62 [Auth] Apply Dodam Design System to Login screen and Register screen
  build.gradle.kts
  data/core/src/main/java/com/b1nd/dodam/data/core/model/Place.kt
  data/core/src/main/java/com/b1nd/dodam/data/core/model/Status.kt
  data/schedule/src/main/java/com/b1nd/dodam/data/schedule/model/Grade.kt
  designsystem/src/main/java/com/b1nd/dodam/designsystem/util/ClassInfoVisualTransformation.kt
  dodam-student/build.gradle.kts
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/MainActivity.kt
  feature/login/build.gradle.kts
  feature/login/src/main/java/com/b1nd/dodam/login/LoginScreen.kt
  feature/login/src/main/java/com/b1nd/dodam/login/model/LoginUiState.kt
  feature/login/src/main/java/com/b1nd/dodam/login/navigation/LoginNavigation.kt
  feature/login/src/main/java/com/b1nd/dodam/login/viewmodel/LoginViewModel.kt
  feature/onboarding/build.gradle.kts
  feature/onboarding/src/main/java/com/b1nd/dodam/onboarding/OnboardingScreen.kt
  feature/register/build.gradle.kts
  feature/register/src/main/java/com/b1nd/dodam/register/AuthScreen.kt
  feature/register/src/main/java/com/b1nd/dodam/register/InfoScreen.kt
  feature/register/src/main/java/com/b1nd/dodam/register/navigation/AuthNavigation.kt
  feature/register/src/main/java/com/b1nd/dodam/register/navigation/InfoNavigation.kt
  feature/register/src/main/java/com/b1nd/dodam/register/state/RegisterUiState.kt
  feature/register/src/main/java/com/b1nd/dodam/register/state/TextFieldState.kt
  feature/register/src/main/java/com/b1nd/dodam/register/viewmodel/RegisterViewModel.kt
  gradle/libs.versions.toml
  settings.gradle.kts
  ui/.gitignore
  ui/build.gradle.kts
  ui/src/main/java/com/b1nd/dodam/ui/icons/Icons.kt
  ui/src/main/java/com/b1nd/dodam/ui/util/FocusCleaner.kt
  ui/src/main/java/com/b1nd/dodam/ui/util/PhoneVisualTransformation.kt
  ui/src/main/res/drawable/ic_b1ndlogo.xml
  ui/src/main/res/drawable/ic_dodamlogo.xml
Labels: refactoring

#66 [Home] Apply Dodam Design System to Home screen
  build-logic/src/main/kotlin/com/b1nd/dodam/primitive/AndroidComposePlugin.kt
  build.gradle.kts
  data/schedule/src/main/java/com/b1nd/dodam/data/schedule/model/Schedule.kt
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/MainActivity.kt
  feature-student/home/build.gradle.kts
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/HomeScreen.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/HomeViewModel.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/card/BannerCard.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/card/MealCard.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/card/NightStudyCard.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/card/OutCard.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/card/ScheduleCard.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/card/WakeupSongCard.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/model/HomeUiState.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/navigation/HomeNavigation.kt
  feature-student/main/build.gradle.kts
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/MainScreen.kt
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/navigation/MainNavigation.kt
  gradle/libs.versions.toml
  network/schedule/src/main/java/com/b1nd/dodam/network/schedule/model/ScheduleResponse.kt
  ui-test-main/src/main/kotlin/com/b1nd/dodam/test/DodamApp.kt
  ui-test-main/src/main/kotlin/com/b1nd/dodam/test/MainActivity.kt
Labels: refactoring

#68 [Out] Create ask out screen
  data/outing/src/main/java/com/b1nd/dodam/data/outing/OutingRepository.kt
  data/outing/src/main/java/com/b1nd/dodam/data/outing/repository/OutingRepositoryImpl.kt
  dodam-student/build.gradle.kts
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  feature-student/all/src/main/java/com/b1nd/dodam/member/AllScreen.kt
  feature-student/ask-out/.gitignore
  feature-student/ask-out/build.gradle.kts
  feature-student/ask-out/consumer-rules.pro
  feature-student/ask-out/proguard-rules.pro
  feature-student/ask-out/src/main/AndroidManifest.xml
  feature-student/ask-out/src/main/java/com/b1nd/dodam/askout/AskOutScreen.kt
  feature-student/ask-out/src/main/java/com/b1nd/dodam/askout/AskOutViewModel.kt
  feature-student/ask-out/src/main/java/com/b1nd/dodam/askout/navigation/AskOutNavigation.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/HomeScreen.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/card/NightStudyCard.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/card/OutCard.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/navigation/HomeNavigation.kt
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/MainScreen.kt
  gradle/libs.versions.toml
  network/outing/src/main/java/com/b1nd/dodam/network/outing/api/OutingService.kt
  network/outing/src/main/java/com/b1nd/dodam/network/outing/datasource/OutingDataSource.kt
  network/outing/src/main/java/com/b1nd/dodam/network/outing/model/OutingRequest.kt
  network/outing/src/main/java/com/b1nd/dodam/network/outing/model/SleepoverRequest.kt
  settings.gradle.kts
  ui/build.gradle.kts
  ui/src/main/java/com/b1nd/dodam/ui/component/InputField.kt
Labels: enhancement
