Repository Team-B1ND/dodamdodam-android, pull requests merged in 2024-11, with the labels that each got.

#225 [Core] Compose Stable Marker
  build-logic/build.gradle.kts
  build-logic/src/main/kotlin/com/b1nd/dodam/dsl/MultiplatformGradleDsl.kt
  build-logic/src/main/kotlin/com/b1nd/dodam/primitive/AndroidComposePlugin.kt
  build-logic/src/main/kotlin/com/b1nd/dodam/primitive/MultiplatformComposePlugin.kt
  gradle/libs.versions.toml
  stable_measure.py
  ui/build.gradle.kts
  ui/src/commonMain/kotlin/com/b1nd/dodam/ui/component/modifier/DropShadowModifier.kt
  ui/src/iosMain/kotlin/com/b1nd/dodam/ui/component/modifier/DropShadowModifier.ios.kt
  ui/src/main/java/com/b1nd/dodam/ui/component/modifier/DropShadowModifier.android.kt
Labels: enhancement

#227 [Core] CD Pipeline
  .github/workflows/cd.yml
  dodam-teacher-android/build.gradle.kts
  gradle/libs.versions.toml
Labels: enhancement

#229 [Student] All Screen DDS version UP To 1.0.9
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  feature-student/all/build.gradle.kts
  feature-student/all/src/main/java/com/b1nd/dodam/member/AllScreen.kt
  feature-student/all/src/main/java/com/b1nd/dodam/member/navigation/AllNavigation.kt
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/MainScreen.kt
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/navigation/MainNavigation.kt
Labels: refactoring

#231 [Student] Ask Night Study Screen dds version up to 1.0.9
  common/src/commonMain/kotlin/com/b1nd/dodam/common/utiles/Utiles.kt
  common/src/iosMain/kotlin/com/b1nd/dodam/common/utiles/Utiles.ios.kt
  common/src/main/java/com/b1nd/dodam/common/utiles/Utiles.android.kt
  feature-student/ask-nightstudy/build.gradle.kts
  feature-student/ask-nightstudy/src/main/java/com/b1nd/dodam/asknightstudy/AskNightStudyScreen.kt
  feature-student/ask-nightstudy/src/main/java/com/b1nd/dodam/asknightstudy/AskNightStudyViewModel.kt
  ui/src/commonMain/kotlin/com/b1nd/dodam/ui/icons/UpDownArrow.kt
Labels: refactoring

#233 [Student] Ask Wakeup Song DDS Version UP
  feature-student/ask-wakeup-song/build.gradle.kts
  feature-student/ask-wakeup-song/src/main/java/com/b1nd/dodam/askwakeupsong/AskWakeupSongScreen.kt
Labels: enhancement, refactoring

#235 [Student] Bus DDS Version Up to 1.0.9
  feature-student/bus/build.gradle.kts
  feature-student/bus/src/main/java/com/b1nd/dodam/bus/BusScreen.kt
  ui/src/commonMain/kotlin/com/b1nd/dodam/ui/component/InputField.kt
Labels: refactoring

#240 [Student] Fix Home Progress
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/card/NightStudyCard.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/card/OutCard.kt
  gradle/libs.versions.toml
Labels: bug

#243 [Student] Version Up to Point Screen DDS 1.1.12
  feature-student/all/src/main/java/com/b1nd/dodam/member/AllScreen.kt
  feature-student/point/build.gradle.kts
  feature-student/point/src/main/java/com/b1nd/dodam/student/point/PointScreen.kt
  feature-student/point/src/main/java/com/b1nd/dodam/student/point/PointViewModel.kt
  feature-teacher/all/src/commonMain/kotlin/com/b1nd/dodam/all/AllScreen.kt
Labels: enhancement

#247 [Student] Version Up to Wakeup Song Screen DDS 1.1.12
  feature-student/point/src/main/java/com/b1nd/dodam/student/point/PointScreen.kt
  feature-student/wakeup-song/build.gradle.kts
  feature-student/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/WakeupSongScreen.kt
Labels: enhancement

#248 [Student] Out Screen DDS Version up to 1.1.0
  dodam-student/build.gradle.kts
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  feature-student/ask-nightstudy/build.gradle.kts
  feature-student/ask-out/build.gradle.kts
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/card/OutCard.kt
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/NightStudyScreen.kt
  feature-student/outing/build.gradle.kts
  feature-student/outing/src/main/java/com/b1nd/dodam/outing/OutScreen.kt
  feature-student/point/src/main/java/com/b1nd/dodam/student/point/PointScreen.kt
  feature-student/register/.gitignore
  feature-student/register/build.gradle.kts
  feature-student/register/consumer-rules.pro
  feature-student/register/proguard-rules.pro
  feature-student/register/src/main/AndroidManifest.xml
  feature-student/register/src/main/java/com/b1nd/dodam/register/AuthScreen.kt
  feature-student/register/src/main/java/com/b1nd/dodam/register/InfoScreen.kt
  feature-student/register/src/main/java/com/b1nd/dodam/register/di/ViewModelModule.kt
  feature-student/register/src/main/java/com/b1nd/dodam/register/navigation/AuthNavigation.kt
  feature-student/register/src/main/java/com/b1nd/dodam/register/navigation/InfoNavigation.kt
  feature-student/register/src/main/java/com/b1nd/dodam/register/state/RegisterUiState.kt
  feature-student/register/src/main/java/com/b1nd/dodam/register/state/TextFieldState.kt
  feature-student/register/src/main/java/com/b1nd/dodam/register/viewmodel/RegisterViewModel.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: refactoring

#251 [Core] Meal screen date issue
  feature/meal/src/commonMain/kotlin/com/b1nd/dodam/meal/MealScreen.kt
Labels: bug

#254 [Core] Add CI Title Checker
  .github/workflows/ci.yml
Labels: enhancement

#255 [Core] Add Student and Teacher deploy the same time
  .github/workflows/cd.yml
Labels: enhancement

#256 [Core] Create Edit Member Info Feature
  %25%23ok%C3%A9k%C3%89%C8%A2
  a%20test%20%26
  data/member/src/commonMain/kotlin/com/b1nd/dodam/member/MemberRepository.kt
  data/member/src/commonMain/kotlin/com/b1nd/dodam/member/repository/MemberRepositoryImpl.kt
  data/upload/.gitignore
  data/upload/build.gradle.kts
  data/upload/src/commonMain/kotlin/com/b1nd/dodam/data/upload/UploadRepository.kt
  data/upload/src/commonMain/kotlin/com/b1nd/dodam/data/upload/di/RepositoryModule.kt
  data/upload/src/commonMain/kotlin/com/b1nd/dodam/data/upload/model/UploadModel.kt
  data/upload/src/commonMain/kotlin/com/b1nd/dodam/data/upload/repository/UploadRepositoryImpl.kt
  dodam-student/build.gradle.kts
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/util/DodamApplication.kt
  dodam-teacher-android/build.gradle.kts
  dodam-teacher-android/src/commonMain/kotlin/com/b1nd/dodam/teacher/DodamTeacherApp.kt
  dodam-teacher-android/src/commonMain/kotlin/com/b1nd/dodam/teacher/Koin.kt
  feature-student/all/src/main/java/com/b1nd/dodam/member/AllScreen.kt
  feature-student/all/src/main/java/com/b1nd/dodam/member/AllViewModel.kt
  feature-teacher/all/src/commonMain/kotlin/com/b1nd/dodam/all/AllScreen.kt
  feature/edit-member-info/.gitignore
  feature/edit-member-info/build.gradle.kts
  feature/edit-member-info/src/commonMain/kotlin/com/b1nd/dodam/editmemberinfo/EditMemberInfoScreen.kt
  feature/edit-member-info/src/commonMain/kotlin/com/b1nd/dodam/editmemberinfo/di/ViewModelModule.kt
  feature/edit-member-info/src/commonMain/kotlin/com/b1nd/dodam/editmemberinfo/model/EditMemberInfoSideEffect.kt
  feature/edit-member-info/src/commonMain/kotlin/com/b1nd/dodam/editmemberinfo/model/ProfileModel.kt
  feature/edit-member-info/src/commonMain/kotlin/com/b1nd/dodam/editmemberinfo/navigation/EditMemberInfoNavigation.kt
  feature/edit-member-info/src/commonMain/kotlin/com/b1nd/dodam/editmemberinfo/viewmodel/EditMemberInfoViewModel.kt
  feature/setting/src/commonMain/kotlin/com/b1nd/dodam/setting/SettingScreen.kt
  feature/setting/src/commonMain/kotlin/com/b1nd/dodam/setting/SettingViewModel.kt
  feature/setting/src/commonMain/kotlin/com/b1nd/dodam/setting/model/SettingUiState.kt
  feature/setting/src/commonMain/kotlin/com/b1nd/dodam/setting/navigation/SettingNavigation.kt
  network/core/src/commonMain/kotlin/com/b1nd/dodam/network/core/DodamUrl.kt
  network/member/src/commonMain/kotlin/com/b1nd/dodam/member/api/MemberService.kt
  network/member/src/commonMain/kotlin/com/b1nd/dodam/member/datasource/MemberDataSource.kt
  network/member/src/commonMain/kotlin/com/b1nd/dodam/member/model/EditMemberInfoRequest.kt
  network/schedule/src/commonMain/kotlin/com/b1nd/dodam/network/schedule/di/DataSourceModule.kt
  network/upload/.gitignore
  network/upload/build.gradle.kts
  network/upload/src/commonMain/kotlin/com/b1nd/dodam/network/upload/api/UploadService.kt
  network/upload/src/commonMain/kotlin/com/b1nd/dodam/network/upload/datasource/UploadDataSource.kt
  network/upload/src/commonMain/kotlin/com/b1nd/dodam/network/upload/di/DataSourceModule.kt
  network/upload/src/commonMain/kotlin/com/b1nd/dodam/network/upload/model/UploadResponse.kt
  settings.gradle.kts
Labels: enhancement

#258 [Teacher] Fix Now Outing Visible Student Error
  feature-teacher/outing/src/commonMain/kotlin/com.b1nd.dodam.outing/OutScreen.kt
Labels: enhancement

#260 [Student] Fix Double Click to Double Request
  feature-student/ask-nightstudy/src/main/java/com/b1nd/dodam/asknightstudy/AskNightStudyScreen.kt
  feature-student/ask-out/src/main/java/com/b1nd/dodam/askout/AskOutScreen.kt
  feature-student/bus/src/main/java/com/b1nd/dodam/bus/BusScreen.kt
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/NightStudyScreen.kt
  feature-student/outing/src/main/java/com/b1nd/dodam/outing/OutScreen.kt
  feature/edit-member-info/src/commonMain/kotlin/com/b1nd/dodam/editmemberinfo/EditMemberInfoScreen.kt
  feature/login/src/commonMain/kotlin/com/b1nd/dodam/login/LoginScreen.kt
Labels: enhancement

#262 [Teacher] Fix Double Click to Double Request
  feature-teacher/all/src/commonMain/kotlin/com/b1nd/dodam/all/AllScreen.kt
  feature-teacher/approve-nightstudy/src/commonMain/kotlin/com/b1nd/dodam/approvenightstudy/ApproveNightStudyScreen.kt
  feature-teacher/approve-outing/src/commonMain/kotlin/com/b1nd/dodam/approveouting/ApproveOutScreen.kt
  feature-teacher/point/src/commonMain/kotlin/com/b1nd/dodam/point/PointScreen.kt
  feature-teacher/point/src/commonMain/kotlin/com/b1nd/dodam/point/screen/GiveScreen.kt
  feature-teacher/point/src/commonMain/kotlin/com/b1nd/dodam/point/screen/SelectScreen.kt
  feature-teacher/register/src/commonMain/kotlin/com/b1nd/dodam/register/AuthScreen.kt
  gradle/libs.versions.toml
Labels: bug
