Repository Team-B1ND/dodamdodam-android, pull requests merged in 2024-07, with the labels that each got.

#142 Expansion of application period
  feature-student/ask-out/src/main/java/com/b1nd/dodam/askout/AskOutScreen.kt
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/NightStudyScreen.kt
  feature-student/outing/src/main/java/com/b1nd/dodam/outing/OutScreen.kt
  gradle/libs.versions.toml
Labels: bug

#138 [Banner] Refactor DI Hilt to Koin
  data/banner/build.gradle.kts
  data/banner/src/main/java/com/b1nd/dodam/data/banner/di/RepositoryModule.kt
  dodam-student/build.gradle.kts
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/util/DodamApplication.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/HomeViewModel.kt
  network/banner/build.gradle.kts
  network/banner/src/main/java/com/b1nd/dodam/network/banner/di/DataSourceModule.kt
Labels: refactoring

#140 [Schedule] Refactor DI Hilt to Koin
  data/schedule/build.gradle.kts
  data/schedule/src/main/java/com/b1nd/dodam/data/schedule/di/RepositoryModule.kt
  dodam-student/build.gradle.kts
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/util/DodamApplication.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/HomeViewModel.kt
  network/schedule/build.gradle.kts
  network/schedule/src/main/java/com/b1nd/dodam/network/schedule/di/DatasourceModule.kt
Labels: refactoring

#145 [Point] Refactor DI Hilt to Koin
  data/point/build.gradle.kts
  data/point/src/main/java/com/b1nd/dodam/data/point/di/RepositoryModule.kt
  dodam-student/build.gradle.kts
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/util/DodamApplication.kt
  feature-student/point/build.gradle.kts
  feature-student/point/src/main/java/com/b1nd/dodam/student/point/PointViewModel.kt
  network/point/build.gradle.kts
  network/point/src/main/java/com/b1nd/dodam/network/point/di/DataSourceModule.kt
Labels: enhancement

#147 [Register] Refactor DI Hilt to Koin
  data/register/build.gradle.kts
  data/register/src/main/java/com/b1nd/dodam/register/di/RepositoryModule.kt
  dodam-student/build.gradle.kts
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/util/DodamApplication.kt
  feature/register/build.gradle.kts
  feature/register/src/main/java/com/b1nd/dodam/register/viewmodel/RegisterViewModel.kt
  network/register/build.gradle.kts
  network/register/src/main/java/com/b1nd/dodam/register/di/DataSourceModule.kt
Labels: refactoring

#149 [Member] Refactor DI Hilt to Koin
  data/member/build.gradle.kts
  data/member/src/main/java/com/b1nd/dodam/member/di/RepositoryModule.kt
  dodam-student/build.gradle.kts
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/util/DodamApplication.kt
  feature-student/all/build.gradle.kts
  feature-student/all/src/main/java/com/b1nd/dodam/member/AllViewModel.kt
  feature/setting/build.gradle.kts
  feature/setting/src/main/java/com/b1nd/dodam/setting/SettingViewModel.kt
  network/member/build.gradle.kts
  network/member/src/main/java/com/b1nd/dodam/member/di/DataSourceModule.kt
Labels: refactoring

#143 Expansion of application period
  feature-student/ask-out/src/main/java/com/b1nd/dodam/askout/AskOutScreen.kt
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/NightStudyScreen.kt
  feature-student/outing/src/main/java/com/b1nd/dodam/outing/OutScreen.kt
  gradle/libs.versions.toml
Labels: bug

#151 [Login] Refactor DI Hilt to Koin
  data/login/build.gradle.kts
  data/login/src/main/java/com/b1nd/dodam/data/login/di/RepositoryModule.kt
  dodam-student/build.gradle.kts
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/util/DodamApplication.kt
  feature/login/build.gradle.kts
  feature/login/src/main/java/com/b1nd/dodam/login/viewmodel/LoginViewModel.kt
  network/login/build.gradle.kts
  network/login/src/main/java/com/b1nd/dodam/network/login/di/DataSourceModule.kt
Labels: refactoring
