Repository Team-B1ND/dodamdodam-android, pull requests merged in 2024-04, with the labels that each got.

#73 [WakeUpSong] Create wake up song
  data/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/WakeupSongRepository.kt
  data/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/model/WakeupSong.kt
  data/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/repository/WakeupSongRepositoryImpl.kt
  dodam-student/build.gradle.kts
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/MainActivity.kt
  feature-student/all/src/main/java/com/b1nd/dodam/member/AllScreen.kt
  feature-student/all/src/main/res/drawable/ic_default_profile.png
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/HomeScreen.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/card/MealCard.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/navigation/HomeNavigation.kt
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/MainScreen.kt
  feature-student/wakeup-song/.gitignore
  feature-student/wakeup-song/build.gradle.kts
  feature-student/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/WakeupSongScreen.kt
  feature-student/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/WakeupSongUiState.kt
  feature-student/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/navigation/OutingNavigation.kt
  feature-student/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/viewmodel/WakeupSongViewModel.kt
  gradle/libs.versions.toml
  network/core/src/main/java/com/b1nd/dodam/network/core/DodamUrl.kt
  network/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/api/WakeupSongService.kt
  network/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/datasource/WakeupSongDataSource.kt
  network/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/model/WakeupSongResponse.kt
  settings.gradle.kts
  ui/src/main/java/com/b1nd/dodam/ui/util/NoInteractionSource.kt
Labels: enhancement

#75 Apply DDS to NightStudy screen, Out screen, Meal screen and improve the quality
  data/core/src/main/java/com/b1nd/dodam/data/core/model/Place.kt
  data/night-study/src/main/java/com/b1nd/dodam/data/nightstudy/NightStudyRepository.kt
  data/night-study/src/main/java/com/b1nd/dodam/data/nightstudy/repository/NightStudyRepositoryImpl.kt
  data/outing/build.gradle.kts
  data/outing/src/main/java/com/b1nd/dodam/data/outing/OutingRepository.kt
  data/outing/src/main/java/com/b1nd/dodam/data/outing/repository/OutingRepositoryImpl.kt
  data/schedule/src/main/java/com/b1nd/dodam/data/schedule/model/Schedule.kt
  designsystem/src/main/java/com/b1nd/dodam/designsystem/component/Card.kt
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  feature-student/all/src/main/java/com/b1nd/dodam/member/AllScreen.kt
  feature-student/all/src/main/java/com/b1nd/dodam/member/navigation/AllNavigation.kt
  feature-student/ask-nightstudy/src/main/java/com/b1nd/dodam/asknightstudy/AskNightStudyScreen.kt
  feature-student/ask-nightstudy/src/main/java/com/b1nd/dodam/asknightstudy/AskNightStudyViewModel.kt
  feature-student/ask-nightstudy/src/main/java/com/b1nd/dodam/asknightstudy/navigation/AskNightStudyNavigation.kt
  feature-student/ask-out/src/main/java/com/b1nd/dodam/askout/AskOutScreen.kt
  feature-student/ask-out/src/main/java/com/b1nd/dodam/askout/navigation/AskOutNavigation.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/HomeScreen.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/navigation/HomeNavigation.kt
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/MainScreen.kt
  feature-student/nightstudy/build.gradle.kts
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/NightStudyScreen.kt
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/NightStudyUiState.kt
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/navigation/NightStudyNavigation.kt
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/viewmodel/NightStudyViewModel.kt
  feature-student/outing/build.gradle.kts
  feature-student/outing/src/main/java/com/b1nd/dodam/outing/OutingScreen.kt
  feature-student/outing/src/main/java/com/b1nd/dodam/outing/OutingUiState.kt
  feature-student/outing/src/main/java/com/b1nd/dodam/outing/nanigation/OutingNavigation.kt
  feature-student/outing/src/main/java/com/b1nd/dodam/outing/viewmodel/OutingViewModel.kt
  feature/login/src/main/java/com/b1nd/dodam/login/navigation/LoginNavigation.kt
  feature/meal/build.gradle.kts
  feature/meal/src/main/java/com/b1nd/dodam/meal/MealScreen.kt
  feature/meal/src/main/java/com/b1nd/dodam/meal/MealUiState.kt
  feature/meal/src/main/java/com/b1nd/dodam/meal/navigation/MealNavigation.kt
  feature/meal/src/main/java/com/b1nd/dodam/meal/viewmodel/MealViewModel.kt
  feature/register/src/main/java/com/b1nd/dodam/register/navigation/AuthNavigation.kt
  feature/register/src/main/java/com/b1nd/dodam/register/navigation/InfoNavigation.kt
  gradle/libs.versions.toml
  network/core/src/main/java/com/b1nd/dodam/network/core/model/NetworkPlace.kt
  network/night-study/src/main/java/com/b1nd/dodam/network/nightstudy/api/NightStudyService.kt
  network/night-study/src/main/java/com/b1nd/dodam/network/nightstudy/datasource/NightStudyDataSource.kt
  network/night-study/src/main/java/com/b1nd/dodam/network/nightstudy/model/NightStudyRequest.kt
  network/outing/src/main/java/com/b1nd/dodam/network/outing/api/OutingService.kt
  network/outing/src/main/java/com/b1nd/dodam/network/outing/datasource/OutingDataSource.kt
  network/schedule/src/main/java/com/b1nd/dodam/network/schedule/model/ScheduleResponse.kt
  ui/src/main/java/com/b1nd/dodam/ui/component/DodamCard.kt
  ui/src/main/java/com/b1nd/dodam/ui/icons/ConvenienceStore.kt
  ui/src/main/java/com/b1nd/dodam/ui/icons/SmileMoon.kt
  ui/src/main/java/com/b1nd/dodam/ui/icons/Tent.kt
Labels: enhancement, refactoring

#79 [Bus] Create bus screen
  data/bus/.gitignore
  data/bus/build.gradle.kts
  data/bus/src/main/java/com/b1nd/dodam/bus/di/RepositoryModule.kt
  data/bus/src/main/java/com/b1nd/dodam/bus/model/Bus.kt
  data/bus/src/main/java/com/b1nd/dodam/bus/repository/BusRepository.kt
  data/bus/src/main/java/com/b1nd/dodam/bus/repositoryimpl/BusRepositoryImpl.kt
  data/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/model/WakeupSong.kt
  dodam-student/build.gradle.kts
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  feature-student/bus/.gitignore
  feature-student/bus/build.gradle.kts
  feature-student/bus/consumer-rules.pro
  feature-student/bus/proguard-rules.pro
  feature-student/bus/src/main/AndroidManifest.xml
  feature-student/bus/src/main/java/com/b1nd/dodam/bus/BusScreen.kt
  feature-student/bus/src/main/java/com/b1nd/dodam/bus/BusViewModel.kt
  feature-student/bus/src/main/java/com/b1nd/dodam/bus/model/BusUiState.kt
  feature-student/bus/src/main/java/com/b1nd/dodam/bus/navigation/BusNavigation.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/card/WakeupSongCard.kt
  feature-student/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/WakeupSongScreen.kt
  network/bus/.gitignore
  network/bus/build.gradle.kts
  network/bus/src/main/java/com/b1nd/dodam/bus/api/BusService.kt
  network/bus/src/main/java/com/b1nd/dodam/bus/datasource/BusDataSource.kt
  network/bus/src/main/java/com/b1nd/dodam/bus/di/DataSourceModule.kt
  network/bus/src/main/java/com/b1nd/dodam/bus/model/BusResponse.kt
  network/core/src/main/java/com/b1nd/dodam/network/core/DodamUrl.kt
  network/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/model/WakeupSongResponse.kt
  settings.gradle.kts
Labels: enhancement

#81 [Point] Create point screen
  data/core/src/main/java/com/b1nd/dodam/data/core/model/Teacher.kt
  data/point/.gitignore
  data/point/build.gradle.kts
  data/point/consumer-rules.pro
  data/point/proguard-rules.pro
  data/point/src/main/java/com/b1nd/dodam/data/point/PointRepository.kt
  data/point/src/main/java/com/b1nd/dodam/data/point/di/RepositoryModule.kt
  data/point/src/main/java/com/b1nd/dodam/data/point/model/Point.kt
  data/point/src/main/java/com/b1nd/dodam/data/point/model/PointReason.kt
  data/point/src/main/java/com/b1nd/dodam/data/point/model/PointType.kt
  data/point/src/main/java/com/b1nd/dodam/data/point/model/ScoreType.kt
  data/point/src/main/java/com/b1nd/dodam/data/point/repository/PointRepositoryImpl.kt
  dodam-student/build.gradle.kts
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  feature-student/point/.gitignore
  feature-student/point/build.gradle.kts
  feature-student/point/src/main/java/com/b1nd/dodam/student/point/PointScreen.kt
  feature-student/point/src/main/java/com/b1nd/dodam/student/point/PointViewModel.kt
  feature-student/point/src/main/java/com/b1nd/dodam/student/point/model/PointUiState.kt
  feature-student/point/src/main/java/com/b1nd/dodam/student/point/navigation/PointNavigation.kt
  feature/onboarding/src/main/java/com/b1nd/dodam/onboarding/OnboardingScreen.kt
  network/core/src/main/java/com/b1nd/dodam/network/core/DodamUrl.kt
  network/core/src/main/java/com/b1nd/dodam/network/core/model/TeacherResponse.kt
  network/point/.gitignore
  network/point/build.gradle.kts
  network/point/consumer-rules.pro
  network/point/proguard-rules.pro
  network/point/src/main/java/com/b1nd/dodam/network/point/api/PointService.kt
  network/point/src/main/java/com/b1nd/dodam/network/point/datasource/PointDataSource.kt
  network/point/src/main/java/com/b1nd/dodam/network/point/di/DataSourceModule.kt
  network/point/src/main/java/com/b1nd/dodam/network/point/model/NetworkPointType.kt
  network/point/src/main/java/com/b1nd/dodam/network/point/model/NetworkScoreType.kt
  network/point/src/main/java/com/b1nd/dodam/network/point/model/PointReasonResponse.kt
  network/point/src/main/java/com/b1nd/dodam/network/point/model/PointResponse.kt
  settings.gradle.kts
Labels: enhancement

#82 [WakeUpSong] Create ask wake up song screen
  common/src/main/java/com/b1nd/dodam/common/exception/DodamException.kt
  data/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/WakeupSongRepository.kt
  data/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/model/MelonChartSong.kt
  data/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/model/SearchWakeupSong.kt
  data/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/repository/WakeupSongRepositoryImpl.kt
  dodam-student/build.gradle.kts
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  feature-student/all/src/main/java/com/b1nd/dodam/member/AllScreen.kt
  feature-student/ask-out/src/main/java/com/b1nd/dodam/askout/AskOutScreen.kt
  feature-student/ask-wakeup-song/.gitignore
  feature-student/ask-wakeup-song/build.gradle.kts
  feature-student/ask-wakeup-song/consumer-rules.pro
  feature-student/ask-wakeup-song/proguard-rules.pro
  feature-student/ask-wakeup-song/src/main/AndroidManifest.xml
  feature-student/ask-wakeup-song/src/main/java/com/b1nd/dodam/askwakeupsong/AskWakeupSongScreen.kt
  feature-student/ask-wakeup-song/src/main/java/com/b1nd/dodam/askwakeupsong/AskWakeupSongViewModel.kt
  feature-student/ask-wakeup-song/src/main/java/com/b1nd/dodam/askwakeupsong/model/AskWakeupSongUiState.kt
  feature-student/ask-wakeup-song/src/main/java/com/b1nd/dodam/askwakeupsong/navigation/AskWakeupSongNavigation.kt
  feature-student/bus/src/main/java/com/b1nd/dodam/bus/BusScreen.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/HomeScreen.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/navigation/HomeNavigation.kt
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/MainScreen.kt
  feature-student/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/WakeupSongScreen.kt
  feature/meal/src/main/java/com/b1nd/dodam/meal/MealScreen.kt
  network/core/src/main/java/com/b1nd/dodam/network/core/DodamUrl.kt
  network/core/src/main/java/com/b1nd/dodam/network/core/util/ApiRequest.kt
  network/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/api/WakeupSongService.kt
  network/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/datasource/WakeupSongDataSource.kt
  network/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/model/MelonChartSongResponse.kt
  network/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/model/SearchWakeupSongRequest.kt
  network/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/model/SearchWakeupSongResponse.kt
  settings.gradle.kts
Labels: enhancement

#84 Make CI builds in parallel
  .github/workflows/ci.yml
Labels: environment

#88 Fix many bugs and home navigation to schedule dialog
  feature-student/ask-wakeup-song/src/main/java/com/b1nd/dodam/askwakeupsong/AskWakeupSongScreen.kt
  feature-student/bus/src/main/java/com/b1nd/dodam/bus/BusScreen.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/HomeScreen.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/card/OutCard.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/card/ScheduleCard.kt
Labels: bug, enhancement

#90 Add padding outing, nightstudy page and Remove default splish
  common/src/main/java/com/b1nd/dodam/common/exception/DodamException.kt
  data/night-study/src/main/java/com/b1nd/dodam/data/nightstudy/model/NightStudy.kt
  data/outing/src/main/java/com/b1nd/dodam/data/outing/model/Outing.kt
  dodam-student/src/main/res/values/themes.xml
  feature-student/ask-nightstudy/src/main/java/com/b1nd/dodam/asknightstudy/AskNightStudyScreen.kt
  feature-student/ask-wakeup-song/src/main/java/com/b1nd/dodam/askwakeupsong/AskWakeupSongScreen.kt
  feature-student/ask-wakeup-song/src/main/java/com/b1nd/dodam/askwakeupsong/AskWakeupSongViewModel.kt
  feature-student/bus/src/main/java/com/b1nd/dodam/bus/BusScreen.kt
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/NightStudyScreen.kt
  feature-student/outing/src/main/java/com/b1nd/dodam/outing/OutingScreen.kt
  network/core/src/main/java/com/b1nd/dodam/network/core/util/ApiRequest.kt
  network/night-study/src/main/java/com/b1nd/dodam/network/nightstudy/model/NightStudyResponse.kt
  network/outing/src/main/java/com/b1nd/dodam/network/outing/model/OutingResponse.kt
  network/outing/src/main/java/com/b1nd/dodam/network/outing/model/SleepoverResponse.kt
Labels: bug, enhancement

#94 [Register] Fix Auth QA bugs
  feature/login/src/main/java/com/b1nd/dodam/login/LoginScreen.kt
  feature/register/src/main/java/com/b1nd/dodam/register/AuthScreen.kt
  feature/register/src/main/java/com/b1nd/dodam/register/InfoScreen.kt
Labels: bug

#95 [Meal] Refactor meal screen
  data/meal/src/main/java/com/b1nd/dodam/data/meal/MealRepository.kt
  data/meal/src/main/java/com/b1nd/dodam/data/meal/respository/MealRepositoryImpl.kt
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/MainScreen.kt
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/MainScreenState.kt
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/navigation/MainDestination.kt
  feature/meal/src/main/java/com/b1nd/dodam/meal/MealScreen.kt
  feature/meal/src/main/java/com/b1nd/dodam/meal/MealState.kt
  feature/meal/src/main/java/com/b1nd/dodam/meal/MealUiState.kt
  feature/meal/src/main/java/com/b1nd/dodam/meal/viewmodel/MealViewModel.kt
  gradle/libs.versions.toml
Labels: refactoring

#98 Fix popBackStack QA bug in login
  feature-student/all/src/main/java/com/b1nd/dodam/member/navigation/AllNavigation.kt
  feature-student/ask-nightstudy/src/main/java/com/b1nd/dodam/asknightstudy/navigation/AskNightStudyNavigation.kt
  feature-student/ask-out/src/main/java/com/b1nd/dodam/askout/navigation/AskOutNavigation.kt
  feature-student/ask-wakeup-song/src/main/java/com/b1nd/dodam/askwakeupsong/navigation/AskWakeupSongNavigation.kt
  feature-student/bus/src/main/java/com/b1nd/dodam/bus/navigation/BusNavigation.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/navigation/HomeNavigation.kt
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/navigation/MainNavigation.kt
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/navigation/NightStudyNavigation.kt
  feature-student/outing/src/main/java/com/b1nd/dodam/outing/nanigation/OutingNavigation.kt
  feature-student/point/src/main/java/com/b1nd/dodam/student/point/navigation/PointNavigation.kt
  feature-student/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/navigation/OutingNavigation.kt
  feature/login/src/main/java/com/b1nd/dodam/login/navigation/LoginNavigation.kt
  feature/meal/src/main/java/com/b1nd/dodam/meal/navigation/MealNavigation.kt
  feature/onboarding/src/main/java/com/b1nd/dodam/onboarding/navigation/OnboardingNavigation.kt
  feature/register/src/main/java/com/b1nd/dodam/register/navigation/AuthNavigation.kt
  feature/register/src/main/java/com/b1nd/dodam/register/navigation/InfoNavigation.kt
  feature/setting/src/main/java/com/b1nd/dodam/setting/navigation/SettingNavigation.kt
Labels: bug

#99 [Out] Refactor out screen
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/MainActivity.kt
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/MainScreen.kt
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/navigation/MainNavigation.kt
  feature-student/outing/src/main/java/com/b1nd/dodam/outing/OutScreen.kt
  feature-student/outing/src/main/java/com/b1nd/dodam/outing/OutScreenState.kt
  feature-student/outing/src/main/java/com/b1nd/dodam/outing/OutingScreen.kt
  feature-student/outing/src/main/java/com/b1nd/dodam/outing/OutingUiState.kt
  feature-student/outing/src/main/java/com/b1nd/dodam/outing/nanigation/OutingNavigation.kt
  feature-student/outing/src/main/java/com/b1nd/dodam/outing/viewmodel/OutViewModel.kt
  feature-student/outing/src/main/java/com/b1nd/dodam/outing/viewmodel/OutingViewModel.kt
  ui-test-main/src/main/kotlin/com/b1nd/dodam/test/DodamApp.kt
Labels: refactoring

#104 [Setting, Wake up song] Add deactivation text / Fix my wake up song design
  data/member/src/main/java/com/b1nd/dodam/member/MemberRepository.kt
  data/member/src/main/java/com/b1nd/dodam/member/repository/MemberRepositoryImpl.kt
  data/wakeup-song/build.gradle.kts
  feature-student/ask-wakeup-song/src/main/java/com/b1nd/dodam/askwakeupsong/AskWakeupSongScreen.kt
  feature-student/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/WakeupSongScreen.kt
  feature/register/src/main/java/com/b1nd/dodam/register/AuthScreen.kt
  feature/register/src/main/java/com/b1nd/dodam/register/InfoScreen.kt
  feature/setting/src/main/java/com/b1nd/dodam/setting/SettingScreen.kt
  feature/setting/src/main/java/com/b1nd/dodam/setting/SettingViewModel.kt
  network/core/src/main/java/com/b1nd/dodam/network/core/DodamUrl.kt
  network/member/src/main/java/com/b1nd/dodam/member/api/MemberService.kt
  network/member/src/main/java/com/b1nd/dodam/member/datasource/MemberDataSource.kt
Labels: bug, enhancement

#102 Implement `Google Analytics` and `Firebase Crashlytics`
  build.gradle.kts
  dodam-student/build.gradle.kts
  dodam-student/google-services.json
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/MainActivity.kt
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/MainScreen.kt
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/MainScreenState.kt
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/navigation/MainNavigation.kt
  gradle/libs.versions.toml
  settings.gradle.kts
  ui-test-main/.gitignore
  ui-test-main/build.gradle.kts
  ui-test-main/proguard-rules.pro
  ui-test-main/src/main/AndroidManifest.xml
  ui-test-main/src/main/kotlin/com/b1nd/dodam/test/DodamApplication.kt
  ui-test-main/src/main/kotlin/com/b1nd/dodam/test/MainActivity.kt
  ui-test-main/src/main/res/drawable/ic_launcher_background.xml
  ui-test-main/src/main/res/drawable/ic_launcher_foreground.xml
  ui-test-main/src/main/res/mipmap-anydpi/ic_launcher.xml
  ui-test-main/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  ui-test-main/src/main/res/mipmap-hdpi/ic_launcher.webp
  ui-test-main/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  ui-test-main/src/main/res/mipmap-mdpi/ic_launcher.webp
  ui-test-main/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  ui-test-main/src/main/res/mipmap-xhdpi/ic_launcher.webp
  ui-test-main/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  ui-test-main/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  ui-test-main/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  ui-test-main/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  ui-test-main/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  ui-test-main/src/main/res/values/colors.xml
  ui-test-main/src/main/res/values/strings.xml
  ui-test-main/src/main/res/values/themes.xml
  ui-test-main/src/main/res/xml/backup_rules.xml
  ui-test-main/src/main/res/xml/data_extraction_rules.xml
Labels: enhancement

#105 [NightStudy] Refactor night study screen
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/MainScreen.kt
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/NightStudyScreen.kt
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/NightStudyScreenState.kt
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/NightStudyUiState.kt
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/navigation/NightStudyNavigation.kt
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/viewmodel/NightStudyViewModel.kt
  feature-student/outing/src/main/java/com/b1nd/dodam/outing/OutScreen.kt
Labels: refactoring

#107 Hoist snackbar to top view
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  feature-student/ask-nightstudy/src/main/java/com/b1nd/dodam/asknightstudy/AskNightStudyScreen.kt
  feature-student/ask-nightstudy/src/main/java/com/b1nd/dodam/asknightstudy/navigation/AskNightStudyNavigation.kt
  feature-student/ask-out/src/main/java/com/b1nd/dodam/askout/AskOutScreen.kt
  feature-student/ask-out/src/main/java/com/b1nd/dodam/askout/navigation/AskOutNavigation.kt
  feature-student/ask-wakeup-song/src/main/java/com/b1nd/dodam/askwakeupsong/AskWakeupSongScreen.kt
  feature-student/ask-wakeup-song/src/main/java/com/b1nd/dodam/askwakeupsong/AskWakeupSongViewModel.kt
  feature-student/ask-wakeup-song/src/main/java/com/b1nd/dodam/askwakeupsong/navigation/AskWakeupSongNavigation.kt
  feature-student/bus/src/main/java/com/b1nd/dodam/bus/BusScreen.kt
  feature-student/bus/src/main/java/com/b1nd/dodam/bus/BusViewModel.kt
  feature-student/bus/src/main/java/com/b1nd/dodam/bus/navigation/BusNavigation.kt
  feature-student/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/WakeupSongScreen.kt
  feature-student/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/navigation/WakeupSongNavigation.kt
Labels: enhancement, refactoring

#108 [WakeUpSong] Fix wake up song bugs
  feature-student/ask-wakeup-song/src/main/java/com/b1nd/dodam/askwakeupsong/AskWakeupSongScreen.kt
  feature-student/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/WakeupSongScreen.kt
  feature-student/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/viewmodel/WakeupSongViewModel.kt
Labels: bug, enhancement

#110 Release 도담도담 v3.0.0
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/MainActivity.kt
  feature-student/all/src/main/java/com/b1nd/dodam/member/AllScreen.kt
  feature-student/ask-nightstudy/src/main/java/com/b1nd/dodam/asknightstudy/AskNightStudyScreen.kt
  feature-student/ask-out/src/main/java/com/b1nd/dodam/askout/AskOutScreen.kt
  feature-student/bus/src/main/java/com/b1nd/dodam/bus/BusScreen.kt
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/MainScreen.kt
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/NightStudyScreen.kt
  feature-student/point/src/main/java/com/b1nd/dodam/student/point/PointScreen.kt
  feature-student/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/WakeupSongScreen.kt
  feature-student/wakeup-song/src/main/java/com/b1nd/dodam/wakeupsong/viewmodel/WakeupSongViewModel.kt
  feature/onboarding/src/main/java/com/b1nd/dodam/onboarding/OnboardingScreen.kt
  feature/setting/src/main/java/com/b1nd/dodam/setting/SettingScreen.kt
  gradle/libs.versions.toml
  network/core/src/main/java/com/b1nd/dodam/network/core/DodamUrl.kt
Labels: release

#112 [Hotfix] Change default message of schedule component on home screen
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/card/ScheduleCard.kt
  gradle/libs.versions.toml
Labels: bug
