Repository Team-B1ND/dodamdodam-android, pull requests merged in 2025-03, with the labels that each got.

#296 [Core] Create Club Remote Logic
  data/club/build.gradle.kts
  data/club/src/commonMain/kotlin/com/b1nd/dodam/club/di/RepositoryModule.kt
  data/club/src/commonMain/kotlin/com/b1nd/dodam/club/model/Club.kt
  data/club/src/commonMain/kotlin/com/b1nd/dodam/club/model/ClubJoin.kt
  data/club/src/commonMain/kotlin/com/b1nd/dodam/club/model/ClubMember.kt
  data/club/src/commonMain/kotlin/com/b1nd/dodam/club/model/ClubPermission.kt
  data/club/src/commonMain/kotlin/com/b1nd/dodam/club/model/ClubState.kt
  data/club/src/commonMain/kotlin/com/b1nd/dodam/club/model/ClubType.kt
  data/club/src/commonMain/kotlin/com/b1nd/dodam/club/repository/ClubRepository.kt
  data/club/src/commonMain/kotlin/com/b1nd/dodam/club/repositoryimpl/ClubRepositoryImpl.kt
  dodam-student/build.gradle.kts
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/util/DodamApplication.kt
  dodam-teacher-android/build.gradle.kts
  dodam-teacher-android/src/commonMain/kotlin/com/b1nd/dodam/teacher/DodamTeacherApp.kt
  dodam-teacher-android/src/commonMain/kotlin/com/b1nd/dodam/teacher/Koin.kt
  feature-teacher/all/src/commonMain/kotlin/com/b1nd/dodam/all/AllScreen.kt
  feature-teacher/all/src/commonMain/kotlin/com/b1nd/dodam/all/navigation/AllNavigation.kt
  feature-teacher/club/build.gradle.kts
  feature-teacher/club/src/commonMain/kotlin/com/b1nd/dodam/club/ClubScreen.kt
  feature-teacher/club/src/commonMain/kotlin/com/b1nd/dodam/club/ClubViewModel.kt
  feature-teacher/club/src/commonMain/kotlin/com/b1nd/dodam/club/di/ViewModelModule.kt
  feature-teacher/club/src/commonMain/kotlin/com/b1nd/dodam/club/model/ClubSideEffect.kt
  feature-teacher/club/src/commonMain/kotlin/com/b1nd/dodam/club/model/ClubUiState.kt
  feature-teacher/club/src/commonMain/kotlin/com/b1nd/dodam/club/navigation/ClubNavigation.kt
  feature-teacher/club/src/commonMain/kotlin/com/b1nd/dodam/club/screen/ClubDetailScreen.kt
  feature-teacher/club/src/commonMain/kotlin/com/b1nd/dodam/club/screen/ClubListScreen.kt
  gradle/libs.versions.toml
  network/club/build.gradle.kts
  network/club/src/commonMain/kotlin/com/b1nd/dodam/club/api/ClubService.kt
  network/club/src/commonMain/kotlin/com/b1nd/dodam/club/datasource/ClubDataSource.kt
  network/club/src/commonMain/kotlin/com/b1nd/dodam/club/di/DataSourceModule.kt
  network/club/src/commonMain/kotlin/com/b1nd/dodam/club/model/ClubJoinResponse.kt
  network/club/src/commonMain/kotlin/com/b1nd/dodam/club/model/ClubMemberResponse.kt
  network/club/src/commonMain/kotlin/com/b1nd/dodam/club/model/ClubResponse.kt
  network/club/src/commonMain/kotlin/com/b1nd/dodam/club/model/request/ClubJoinRequest.kt
  network/club/src/commonMain/kotlin/com/b1nd/dodam/club/model/request/ClubStateRequest.kt
  network/club/src/commonTest/kotlin/com/b1nd/dodam/club/ClubServiceTest.kt
  network/core/src/commonMain/kotlin/com/b1nd/dodam/network/core/DodamUrl.kt
  settings.gradle.kts
  ui/src/commonMain/composeResources/drawable/ic_crown.xml
  ui/src/commonMain/composeResources/drawable/ic_silhouette.xml
  ui/src/commonMain/kotlin/com/b1nd/dodam/ui/icons/Icons.kt
Labels: enhancement

#298 [Student] Create Parent Register
  data/core/src/commonMain/kotlin/com/b1nd/dodam/data/core/model/Children.kt
  data/member/src/commonMain/kotlin/com/b1nd/dodam/member/MemberRepository.kt
  data/member/src/commonMain/kotlin/com/b1nd/dodam/member/repository/MemberRepositoryImpl.kt
  data/register/build.gradle.kts
  data/register/src/commonMain/kotlin/com/b1nd/dodam/register/repository/RegisterRepository.kt
  data/register/src/commonMain/kotlin/com/b1nd/dodam/register/repositoryImpl/RegisterRepositoryImpl.kt
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/util/DodamApplication.kt
  feature-parent/children-manage/src/main/java/com/b1nd/dodam/parent/childrenmanage/ChildrenManageScreen.kt
  feature-parent/children-manage/src/main/java/com/b1nd/dodam/parent/childrenmanage/ChildrenManageViewModel.kt
  feature-parent/children-manage/src/main/java/com/b1nd/dodam/parent/childrenmanage/model/ChildrenModel.kt
  feature-parent/children-manage/src/main/java/com/b1nd/dodam/parent/childrenmanage/navigation/ChildrenManageNavigation.kt
  feature-parent/main/build.gradle.kts
  feature-parent/main/src/main/java/com/b1nd/dodam/parent/main/ParentMainScreen.kt
  feature-student/register/build.gradle.kts
  feature-student/register/src/main/java/com/b1nd/dodam/register/AuthScreen.kt
  feature-student/register/src/main/java/com/b1nd/dodam/register/InfoScreen.kt
  feature-student/register/src/main/java/com/b1nd/dodam/register/SelectRoleScreen.kt
  feature-student/register/src/main/java/com/b1nd/dodam/register/di/ViewModelModule.kt
  feature-student/register/src/main/java/com/b1nd/dodam/register/navigation/AuthNavigation.kt
  feature-student/register/src/main/java/com/b1nd/dodam/register/navigation/InfoNavigation.kt
  feature-student/register/src/main/java/com/b1nd/dodam/register/navigation/SelectRoleNavigation.kt
  feature-student/register/src/main/java/com/b1nd/dodam/register/state/InfoSideEffect.kt
  feature-student/register/src/main/java/com/b1nd/dodam/register/viewmodel/InfoViewModel.kt
  feature-student/register/src/main/java/com/b1nd/dodam/register/viewmodel/RegisterViewModel.kt
  gradle/libs.versions.toml
  network/core/src/commonMain/kotlin/com/b1nd/dodam/network/core/DodamUrl.kt
  network/member/src/commonMain/kotlin/com/b1nd/dodam/member/api/MemberService.kt
  network/member/src/commonMain/kotlin/com/b1nd/dodam/member/datasource/MemberDataSource.kt
  network/member/src/commonMain/kotlin/com/b1nd/dodam/member/model/GetAuthCodeRequest.kt
  network/register/src/commonMain/kotlin/com/b1nd/dodam/register/api/RegisterService.kt
  network/register/src/commonMain/kotlin/com/b1nd/dodam/register/datasource/RegisterDataSource.kt
  network/register/src/commonMain/kotlin/com/b1nd/dodam/register/model/RegisterParentRequest.kt
  ui/src/commonMain/composeResources/drawable/ic_checkmark.xml
  ui/src/commonMain/composeResources/drawable/img_parent.png
  ui/src/commonMain/composeResources/drawable/img_student.png
  ui/src/commonMain/kotlin/com/b1nd/dodam/ui/icons/Icons.kt
Labels: enhancement

#303 [Core] Fix Club Member Response Error
  data/club/src/commonMain/kotlin/com/b1nd/dodam/club/model/ClubMember.kt
  data/club/src/commonMain/kotlin/com/b1nd/dodam/club/model/ClubMemberStudent.kt
  data/club/src/commonMain/kotlin/com/b1nd/dodam/club/repository/ClubRepository.kt
  data/club/src/commonMain/kotlin/com/b1nd/dodam/club/repositoryimpl/ClubRepositoryImpl.kt
  feature-student/club/src/main/java/com/b1nd/dodam/club/ClubViewModel.kt
  feature-student/club/src/main/java/com/b1nd/dodam/club/model/ClubUiState.kt
  feature-student/club/src/main/java/com/b1nd/dodam/club/screen/ClubDetailScreen.kt
  feature-teacher/club/src/commonMain/kotlin/com/b1nd/dodam/club/ClubViewModel.kt
  feature-teacher/club/src/commonMain/kotlin/com/b1nd/dodam/club/model/ClubUiState.kt
  feature-teacher/club/src/commonMain/kotlin/com/b1nd/dodam/club/screen/ClubDetailScreen.kt
  network/club/src/commonMain/kotlin/com/b1nd/dodam/club/api/ClubService.kt
  network/club/src/commonMain/kotlin/com/b1nd/dodam/club/datasource/ClubDataSource.kt
  network/club/src/commonMain/kotlin/com/b1nd/dodam/club/model/ClubMemberResponse.kt
Labels: bug

#307 [Core] Notice File Download Logic
  build-logic/src/main/kotlin/com/b1nd/dodam/primitive/KotlinSerializationPlugin.kt
  data/notice/build.gradle.kts
  data/notice/src/commonMain/kotlin/com/b1nd/dodam/data/notice/model/NoticeFile.kt
  data/notice/src/commonMain/kotlin/com/b1nd/dodam/data/notice/model/NoticeFileType.kt
  dodam-student/build.gradle.kts
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/MainActivity.kt
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/util/DodamApplication.kt
  dodam-teacher-android/build.gradle.kts
  dodam-teacher-android/src/androidMain/AndroidManifest.xml
  dodam-teacher-android/src/androidMain/kotlin/com/b1nd/dodam/teacher/MainActivity.kt
  dodam-teacher-android/src/commonMain/kotlin/com/b1nd/dodam/teacher/DodamTeacherApp.kt
  dodam-teacher-android/src/iosMain/kotlin/com/b1nd/dodam/teacher/MainViewController.kt
  feature-parent/main/src/main/java/com/b1nd/dodam/parent/main/ParentMainScreen.kt
  feature-parent/main/src/main/java/com/b1nd/dodam/parent/main/navigation/ParentMainNavigation.kt
  feature-student/all/src/main/java/com/b1nd/dodam/member/AllScreen.kt
  feature-student/all/src/main/java/com/b1nd/dodam/member/navigation/AllNavigation.kt
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/MainScreen.kt
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/navigation/MainNavigation.kt
  feature-teacher/club/src/commonMain/kotlin/com/b1nd/dodam/club/screen/ClubListScreen.kt
  feature/notice-viewer/.gitignore
  feature/notice-viewer/build.gradle.kts
  feature/notice-viewer/consumer-rules.pro
  feature/notice-viewer/proguard-rules.pro
  feature/notice-viewer/src/commonMain/kotlin/com/b1nd/dodam/noticeviewer/NoticeViewerScreen.kt
  feature/notice-viewer/src/commonMain/kotlin/com/b1nd/dodam/noticeviewer/navigation/NoticeViewerNavigation.kt
  feature/notice/src/commonMain/kotlin/com/b1nd/dodam/notice/NoticeScreen.kt
  feature/notice/src/commonMain/kotlin/com/b1nd/dodam/notice/navigation/NoticeNavigation.kt
  feature/notice/src/commonMain/kotlin/com/b1nd/dodam/notice/viewmodel/NoticeViewModel.kt
  gradle/libs.versions.toml
  settings.gradle.kts
  ui/src/commonMain/kotlin/com/b1nd/dodam/ui/util/FileDownloader.kt
  ui/src/iosMain/kotlin/com/b1nd/dodam/ui/component/util/IOSFileDownloader.kt
  ui/src/main/java/com/b1nd/dodam/ui/util/AndroidFileDownloader.kt
Labels: enhancement

#306 [Student] Create Club List Screen
  build-logic/gradle.properties
  data/club/src/commonMain/kotlin/com/b1nd/dodam/club/model/ClubMyJoined.kt
  data/club/src/commonMain/kotlin/com/b1nd/dodam/club/repository/ClubRepository.kt
  data/club/src/commonMain/kotlin/com/b1nd/dodam/club/repositoryimpl/ClubRepositoryImpl.kt
  dodam-student/google-services.json
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/util/DodamApplication.kt
  feature-student/club/build.gradle.kts
  feature-student/club/src/main/java/com/b1nd/dodam/club/ClubScreen.kt
  feature-student/club/src/main/java/com/b1nd/dodam/club/ClubViewModel.kt
  feature-student/club/src/main/java/com/b1nd/dodam/club/MainClubScreen.kt
  feature-student/club/src/main/java/com/b1nd/dodam/club/MyClubViewModel.kt
  feature-student/club/src/main/java/com/b1nd/dodam/club/di/ViewModelModule.kt
  feature-student/club/src/main/java/com/b1nd/dodam/club/model/ApplySideEffect.kt
  feature-student/club/src/main/java/com/b1nd/dodam/club/model/MyClubUiState.kt
  feature-student/club/src/main/java/com/b1nd/dodam/club/navigation/MyClubNavigation.kt
  feature-student/club/src/main/java/com/b1nd/dodam/club/screen/ClubDetailScreen.kt
  feature-student/club/src/main/java/com/b1nd/dodam/club/screen/ClubListScreen.kt
  feature-student/club/src/main/java/com/b1nd/dodam/club/screen/JoinClubScreen.kt
  feature-student/club/src/main/java/com/b1nd/dodam/club/screen/MyClubScreen.kt
  feature-student/club/src/main/res/drawable/frame.xml
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/HomeViewModel.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/card/MealCard.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/card/NightStudyCard.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/card/OutCard.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/card/ScheduleCard.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/card/WakeupSongCard.kt
  feature-student/main/src/main/java/com/b1nd/dodam/student/main/MainScreen.kt
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
  network/bus/src/commonTest/kotlin/com/b1nd/dodam/bus/BusServiceTest.kt
  network/club/src/commonMain/kotlin/com/b1nd/dodam/club/api/ClubService.kt
  network/club/src/commonMain/kotlin/com/b1nd/dodam/club/datasource/ClubDataSource.kt
  network/club/src/commonMain/kotlin/com/b1nd/dodam/club/model/ClubJoinResponse.kt
  network/club/src/commonMain/kotlin/com/b1nd/dodam/club/model/ClubMyJoinedResponse.kt
  network/club/src/commonMain/kotlin/com/b1nd/dodam/club/model/ClubResponse.kt
  network/club/src/commonMain/kotlin/com/b1nd/dodam/club/model/request/ClubJoinRequest.kt
  network/club/src/commonTest/kotlin/com/b1nd/dodam/club/ClubServiceTest.kt
  network/core/src/commonMain/kotlin/com/b1nd/dodam/network/core/DodamUrl.kt
  network/outing/src/commonTest/kotlin/com/b1nd/dodam/network/outing/OutingServiceTest.kt
  settings.gradle.kts
  ui/src/commonMain/kotlin/com/b1nd/dodam/ui/component/FullIconButton.kt
  ui/src/main/res/drawable/ic_colored_checkmark_circle.xml
  ui/src/main/res/drawable/ic_colored_clock.xml
Labels: enhancement

#309 [Core] Release S3.5.0 T3.2.0
  data/core/src/commonMain/kotlin/com/b1nd/dodam/data/core/model/Children.kt
  data/member/src/commonMain/kotlin/com/b1nd/dodam/member/model/Student.kt
  data/register/src/commonMain/kotlin/com/b1nd/dodam/register/repositoryImpl/RegisterRepositoryImpl.kt
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  dodam-teacher-android/build.gradle.kts
  dodam-teacher-android/src/commonMain/kotlin/com/b1nd/dodam/teacher/DodamTeacherApp.kt
  feature-parent/all/src/main/java/com/b1nd/dodam/all/ParentAllScreen.kt
  feature-parent/all/src/main/java/com/b1nd/dodam/all/navigation/ParentAllNavigation.kt
  feature-parent/children-manage/src/main/java/com/b1nd/dodam/parent/childrenmanage/ChildrenManageScreen.kt
  feature-parent/children-manage/src/main/java/com/b1nd/dodam/parent/childrenmanage/ChildrenManageViewModel.kt
  feature-parent/main/src/main/java/com/b1nd/dodam/parent/main/ParentMainScreen.kt
  feature-parent/main/src/main/java/com/b1nd/dodam/parent/main/navigation/ParentMainNavigation.kt
  feature-student/all/src/main/java/com/b1nd/dodam/member/AllScreen.kt
  feature-student/club/src/main/java/com/b1nd/dodam/club/ClubScreen.kt
  feature-student/club/src/main/java/com/b1nd/dodam/club/MyClubViewModel.kt
  feature-student/club/src/main/java/com/b1nd/dodam/club/model/ApplySideEffect.kt
  feature-student/club/src/main/java/com/b1nd/dodam/club/screen/ClubListScreen.kt
  feature-student/club/src/main/java/com/b1nd/dodam/club/screen/JoinClubScreen.kt
  feature-student/register/src/main/java/com/b1nd/dodam/register/InfoScreen.kt
  feature/notice-viewer/src/commonMain/kotlin/com/b1nd/dodam/noticeviewer/NoticeViewerScreen.kt
  gradle/libs.versions.toml
  network/core/src/androidMain/kotlin/com/b1nd/dodam/network/core/di/NetworkModule.android.kt
  network/core/src/commonMain/kotlin/com/b1nd/dodam/network/core/di/NetworkModule.kt
  network/core/src/iosMain/kotlin/com/b1nd/dodam/network/core/di/NetworkModule.ios.kt
  network/member/src/commonMain/kotlin/com/b1nd/dodam/member/model/StudentResponse.kt
  network/register/src/commonMain/kotlin/com/b1nd/dodam/register/model/RegisterParentRequest.kt
  ui/src/commonMain/composeResources/drawable/ic_colored_credit_card.xml
  ui/src/commonMain/kotlin/com/b1nd/dodam/ui/icons/Icons.kt
Labels: enhancement

#314 [Core] Hotfix Register and Token Issue
  data/login/src/commonMain/kotlin/com/b1nd/dodam/data/login/repository/LoginRepository.kt
  data/login/src/commonMain/kotlin/com/b1nd/dodam/data/login/repositoryimpl/LoginRepositoryImpl.kt
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  dodam-teacher-android/build.gradle.kts
  dodam-teacher-android/src/commonMain/kotlin/com/b1nd/dodam/teacher/DodamTeacherApp.kt
  dodam-teacher-ios/iosApp.xcodeproj/project.pbxproj
  dodam-teacher-ios/iosApp/Info.plist
  feature/setting/build.gradle.kts
  feature/setting/src/commonMain/kotlin/com/b1nd/dodam/setting/SettingViewModel.kt
  gradle/libs.versions.toml
  network/core/src/commonMain/kotlin/com/b1nd/dodam/network/core/util/ClearToken.kt
  network/login/src/commonMain/kotlin/com/b1nd/dodam/network/login/api/LoginService.kt
  network/login/src/commonMain/kotlin/com/b1nd/dodam/network/login/datasource/LoginDataSource.kt
Labels: bug

#324 [Core] Hotfix Student 3.5.2 and Teacher 3.2.2
  %25%23ok%C3%A9k%C3%89%C8%A2
  a%20test%20%26
  data/club/src/commonMain/kotlin/com/b1nd/dodam/club/model/ClubJoin.kt
  dodam-student/google-services.json
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  dodam-teacher-android/build.gradle.kts
  dodam-teacher-android/src/commonMain/kotlin/com/b1nd/dodam/teacher/DodamTeacherApp.kt
  dodam-teacher-ios/iosApp.xcodeproj/project.pbxproj
  dodam-teacher-ios/iosApp/Info.plist
  feature-student/club/src/main/java/com/b1nd/dodam/club/MyClubViewModel.kt
  feature-student/club/src/main/java/com/b1nd/dodam/club/screen/ClubDetailScreen.kt
  feature-student/club/src/main/java/com/b1nd/dodam/club/screen/ClubListScreen.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/card/OutCard.kt
  feature-student/outing/src/main/java/com/b1nd/dodam/outing/OutScreen.kt
  feature/notice/src/commonMain/kotlin/com/b1nd/dodam/notice/NoticeScreen.kt
  feature/notice/src/commonMain/kotlin/com/b1nd/dodam/notice/model/NoticeUiState.kt
  feature/notice/src/commonMain/kotlin/com/b1nd/dodam/notice/viewmodel/NoticeViewModel.kt
  gradle/libs.versions.toml
Labels: bug, enhancement

#323 [Core] Hotfix Student 3.5.2 and Teacher 3.2.2
  data/club/src/commonMain/kotlin/com/b1nd/dodam/club/model/ClubJoin.kt
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  dodam-teacher-android/build.gradle.kts
  dodam-teacher-android/src/commonMain/kotlin/com/b1nd/dodam/teacher/DodamTeacherApp.kt
  dodam-teacher-ios/iosApp.xcodeproj/project.pbxproj
  dodam-teacher-ios/iosApp/Info.plist
  feature-student/club/src/main/java/com/b1nd/dodam/club/MyClubViewModel.kt
  feature-student/club/src/main/java/com/b1nd/dodam/club/screen/ClubDetailScreen.kt
  feature-student/club/src/main/java/com/b1nd/dodam/club/screen/ClubListScreen.kt
  feature-student/home/src/main/java/com/b1nd/dodam/student/home/card/OutCard.kt
  feature-student/outing/src/main/java/com/b1nd/dodam/outing/OutScreen.kt
  feature/notice/src/commonMain/kotlin/com/b1nd/dodam/notice/NoticeScreen.kt
  feature/notice/src/commonMain/kotlin/com/b1nd/dodam/notice/model/NoticeUiState.kt
  feature/notice/src/commonMain/kotlin/com/b1nd/dodam/notice/viewmodel/NoticeViewModel.kt
  gradle/libs.versions.toml
Labels: bug, enhancement

#327 [Core] Hotfix S3.5.3 and T3.2.3
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  dodam-teacher-android/build.gradle.kts
  dodam-teacher-android/src/commonMain/kotlin/com/b1nd/dodam/teacher/DodamTeacherApp.kt
  dodam-teacher-ios/iosApp.xcodeproj/project.pbxproj
  dodam-teacher-ios/iosApp/Info.plist
  feature/notice/src/commonMain/kotlin/com/b1nd/dodam/notice/NoticeScreen.kt
  feature/notice/src/commonMain/kotlin/com/b1nd/dodam/notice/model/NoticeUiState.kt
  feature/notice/src/commonMain/kotlin/com/b1nd/dodam/notice/viewmodel/NoticeViewModel.kt
  gradle/libs.versions.toml
Labels: enhancement

#326 [Core] Hotfix S3.5.3 and T3.2.3
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  dodam-teacher-android/build.gradle.kts
  dodam-teacher-android/src/commonMain/kotlin/com/b1nd/dodam/teacher/DodamTeacherApp.kt
  dodam-teacher-ios/iosApp.xcodeproj/project.pbxproj
  dodam-teacher-ios/iosApp/Info.plist
  feature/notice/src/commonMain/kotlin/com/b1nd/dodam/notice/NoticeScreen.kt
  feature/notice/src/commonMain/kotlin/com/b1nd/dodam/notice/model/NoticeUiState.kt
  feature/notice/src/commonMain/kotlin/com/b1nd/dodam/notice/viewmodel/NoticeViewModel.kt
  gradle/libs.versions.toml
Labels: enhancement
