Repository Team-B1ND/dodamdodam-android, pull requests merged in 2025-05, with the labels that each got.

#333 [Student] Add Project Night Study
  data/core/src/commonMain/kotlin/com/b1nd/dodam/data/core/model/Place.kt
  data/core/src/commonMain/kotlin/com/b1nd/dodam/data/core/model/Student.kt
  data/night-study/src/commonMain/kotlin/com/b1nd/dodam/data/nightstudy/NightStudyRepository.kt
  data/night-study/src/commonMain/kotlin/com/b1nd/dodam/data/nightstudy/model/NightStudy.kt
  data/night-study/src/commonMain/kotlin/com/b1nd/dodam/data/nightstudy/model/NightStudyStudent.kt
  data/night-study/src/commonMain/kotlin/com/b1nd/dodam/data/nightstudy/model/Project.kt
  data/night-study/src/commonMain/kotlin/com/b1nd/dodam/data/nightstudy/repository/NightStudyRepositoryImpl.kt
  feature-student/ask-nightstudy/src/main/java/com/b1nd/dodam/asknightstudy/AskNightStudyScreen.kt
  feature-student/ask-nightstudy/src/main/java/com/b1nd/dodam/asknightstudy/AskNightStudyViewModel.kt
  feature-student/ask-nightstudy/src/main/java/com/b1nd/dodam/asknightstudy/model/AskNightStudyUiState.kt
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/NightStudyScreen.kt
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/viewmodel/NightStudyViewModel.kt
  network/core/src/commonMain/kotlin/com/b1nd/dodam/network/core/DodamUrl.kt
  network/core/src/commonMain/kotlin/com/b1nd/dodam/network/core/model/StudentResponse.kt
  network/night-study/src/commonMain/kotlin/com/b1nd/dodam/network/nightstudy/api/NightStudyService.kt
  network/night-study/src/commonMain/kotlin/com/b1nd/dodam/network/nightstudy/datasource/NightStudyDataSource.kt
  network/night-study/src/commonMain/kotlin/com/b1nd/dodam/network/nightstudy/model/NightStudyRequest.kt
  network/night-study/src/commonMain/kotlin/com/b1nd/dodam/network/nightstudy/model/NightStudyResponse.kt
  network/night-study/src/commonMain/kotlin/com/b1nd/dodam/network/nightstudy/model/NightStudyStudentResponse.kt
  network/night-study/src/commonMain/kotlin/com/b1nd/dodam/network/nightstudy/model/ProjectResponse.kt
Labels: enhancement

#335 [Student] Fix Delete My Project Logic
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/NightStudyScreen.kt
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/viewmodel/NightStudyViewModel.kt
Labels: bug

#339 [Student] Fix Version
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  gradle/libs.versions.toml
Labels: release

#343 [Student] Fix Project Request Logic
  data/night-study/src/commonMain/kotlin/com/b1nd/dodam/data/nightstudy/NightStudyRepository.kt
  data/night-study/src/commonMain/kotlin/com/b1nd/dodam/data/nightstudy/model/MyBan.kt
  data/night-study/src/commonMain/kotlin/com/b1nd/dodam/data/nightstudy/model/NightStudy.kt
  data/night-study/src/commonMain/kotlin/com/b1nd/dodam/data/nightstudy/model/Project.kt
  data/night-study/src/commonMain/kotlin/com/b1nd/dodam/data/nightstudy/repository/NightStudyRepositoryImpl.kt
  feature-student/ask-nightstudy/src/main/java/com/b1nd/dodam/asknightstudy/AskNightStudyScreen.kt
  feature-student/ask-nightstudy/src/main/java/com/b1nd/dodam/asknightstudy/AskNightStudyViewModel.kt
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/NightStudyScreen.kt
  feature-student/nightstudy/src/main/java/com/b1nd/dodam/nightstudy/viewmodel/NightStudyViewModel.kt
  feature-teacher/nightstudy/src/commonMain/kotlin/com/b1nd/dodam/nightstudy/NightStudyScreen.kt
  gradle.properties
  network/night-study/src/commonMain/kotlin/com/b1nd/dodam/network/nightstudy/api/NightStudyService.kt
  network/night-study/src/commonMain/kotlin/com/b1nd/dodam/network/nightstudy/datasource/NightStudyDataSource.kt
  network/night-study/src/commonMain/kotlin/com/b1nd/dodam/network/nightstudy/model/MyBanResponse.kt
  network/night-study/src/commonMain/kotlin/com/b1nd/dodam/network/nightstudy/model/NightStudyRequest.kt
  network/night-study/src/commonMain/kotlin/com/b1nd/dodam/network/nightstudy/model/NightStudyResponse.kt
  network/night-study/src/commonMain/kotlin/com/b1nd/dodam/network/nightstudy/model/ProjectResponse.kt
Labels: bug

#346 [Student] Release 3.6.4
  dodam-student/src/main/kotlin/com/b1nd/dodam/student/DodamApp.kt
  gradle/libs.versions.toml
Labels: release
